name: Update README
 
on:
  push:
    branches:
      - main
 
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update README
      uses: actions/github-script@v5
      with:
        script: |
          const fs = require('fs');
          fs.appendFileSync('README.md', 'New data\n', 'utf8');

