name: Update README
 
on:
  push:
    branches:
      - main
 
jobs:
  update-readme:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
 
      - name: Update README
        run: |
          echo "New Data: $(date)" >> README.md
 
      - name: Commit and Push
        run: |
          git add README.md
          git commit -m "Update README with new data"
          git push origin main
