name: Update README
 
on:
  push:
    branches:
      - main
 
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add data to README
      run: echo "New data" >> README.md
